### ISSUE TITLE
Install more files on Linux

### ISSUE THREAD

**Issue by erazor-de** [orbcode/orbuculum#100]
At the moment the meson `install` target only installs the executables and library.
In my opinion on Linux the `Support/60-orbcode.rules` should be installed to `/lib/udev/rules.d/`.
Also the `Support/gdbtrace.init` is useful enough to be placed in `/usr/share/orbuculum/`.
The need to manually copy this file could lead to people using outdated versions.

**Comment by mubes** [comment]
Fair point. This should now be addressed in [e18db4a](https://github.com/orbcode/orbuculum/commit/e18db4a70ed658d9590719ea57402fdb6b7e8d9a). Please yell up if it still gives you issues.  

Thanks for the feedback.

DAVE
