### ISSUE TITLE
Extraneous arguments in meson.build file

### ISSUE THREAD

**Issue by j-hui** [orbcode/orbuculum#101]
I'm trying to build orbuculum from source, from the `main` branch. I get the following error:

```console
$ meson setup build
The Meson build system
Version: 0.56.2
Source dir: /home/j-hui/extern/orbuculum
Build dir: /home/j-hui/extern/orbuculum/build
Build type: native build
Project name: orbuculum
Project version: undefined
C compiler for the host machine: ccache cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Run-time dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libusb-1.0 found: YES 1.0.24
Run-time dependency libzmq found: YES 4.3.4
Run-time dependency sdl2 found: YES 2.0.14

meson.build:3:0: ERROR: Expected 1 arguments, got 2.

A full log can be found at /home/j-hui/extern/orbuculum/build/meson-logs/meson-log.txt
```

The problem appears to be from the dependencies section, which invokes `dependency('ncurses', 'ncursesw')`. I'm able to work around the problem with either of the following changes:

```diff
-    dependency('ncurses', 'ncursesw')
+    dependency('ncurses')
```

or

```diff
-    dependency('ncurses', 'ncursesw')
+    dependency('ncurses', fallback: ['ncursesw'])
```
 
but I'm wondering if I'm doing something wrong in the first place?

Thanks!

**Comment by zyp** [comment]
Looks like your meson is just too old. This feature was apparently added in 0.60: https://mesonbuild.com/Release-notes-for-0-60-0.html#dependencies-with-multiple-names

**Comment by j-hui** [comment]
I figured it would amount to something like that. My Linux machine is way overdue for an upgrade (: 

Thanks for the help!

**Comment by eli-schwartz** [comment]
> Looks like your meson is just too old. This feature was apparently added in 0.60

I would suggest adding `meson_version: '>=0.60.0'` as a kwarg to your project() function -- then meson will:
- error out if you try building with an older version of meson
- print warnings if you use features introduced *later* than 0.60.0, which is a sign that you should either bump your minimum version or figure out a way to do what you are trying to do without using really new functionality
