### ISSUE TITLE
Cannot set server and port in orbfifo

### ISSUE THREAD

**Issue by LnnrtS** [orbcode/orbuculum#114]
Help does not show these options and they are not parsed.

I though it would be possible to directly connect this to a jlink raw SWO port..

**Comment by mubes** [comment]
Thanks for the report. This should be resolved in https://github.com/orbcode/orbuculum/commit/a48d03ac08948093a5712172d6bef83a3d2ec024 . Could you please take a look and provide feedback.

**Comment by mubes** [comment]
Closed per #116.
