### ISSUE TITLE
Do not require trailing slash in orbfifo basedir

### ISSUE THREAD

**Issue by LnnrtS** [orbcode/orbuculum#115]
If it's meant to be a directory, it should not require trailing slash.  
If it's meant to be a prefix it should be named differently

**Comment by mubes** [comment]
Thanks for the report. This should be resolved in https://github.com/orbcode/orbuculum/commit/a48d03ac08948093a5712172d6bef83a3d2ec024 . Could you please take a look and provide feedback.

**Comment by mubes** [comment]
Closed per #116.
