### ISSUE TITLE
No LAR in ETM or TPIU?

### ISSUE THREAD

**Issue by TomKeddie** [orbcode/orbuculum#156]
Perhaps this is cpu dependent, but as far as I can tell only ITM has a LAR.

https://github.com/orbcode/orbuculum/blob/main/Support/gdbtrace.init#L997

```
set *($ITMBASE+0xfb0) = 0xc5acce55
set *($ETMBASE+0xfb0) = 0xc5acce55
set *($TPIUBASE+0xfb0) = 0xc5acce55
```

**Comment by mubes** [comment]
Agreed! Checked via TRM and coresight documentation. Fixed via #62b3a29. Thanks.
