### ISSUE TITLE
STM32 specific?

### ISSUE THREAD

**Issue by hackrid** [orbcode/orbuculum#21]
Hi all,

I'm wondering if this solution is limited to be used with STM32 as stated in the command
"enableSTM32SWD                          <*--- turn on SWO output pin on CPU"

thansk!

**Comment by mubes** [comment]
The enableSTM32SWD (now enableSTM32SWO) is indeed just for that chip because the SWO needs to be switched on. There may be equivalents for other chip families that will be added eventually...there's one for IMXRT in the blackorb branch, for example.
