### ISSUE TITLE
Devel missing fixes from master

### ISSUE THREAD

**Issue by karlp** [orbcode/orbuculum#35]
Devel branch hasn't picked up fixes from master?  It seems some of them were picked in with other changes, but others have been missed?  eg, master's f6302c9c35bc37775c0cc9bcb44cbbc1f28456e3 is included as part of the unrelated 6f0880eaf1a59f51ce6e8a6c56ad63aade231367 on Devel.  It's at least missing the segfault on orbdump, but the way you've been using git makes it almost impossible to track what you have actually included where.

**Comment by mubes** [comment]
I've reviewed these as part of the switch to the new main/Devel versions. Hopefully everything is folded in correctly now.
