### ISSUE TITLE
orbtop exception tick count wrong for nested instructions

### ISSUE THREAD

**Issue by via** [orbcode/orbuculum#86]
I'm debugging an stm32f427 target using an orbtrace mini, and noticed that the tick counts for the interrupt in question according to orbtop are significantly smaller than a cycle count in code of the exception's running, even taking into account the nested interrupts running during the interrupt.  Digging into orbtop, it looks like an exception trace "Resume" is taken to mean rolling up the entire exception stack to nothing, but that does not seem to be what the actual trace output is doing:
```
1,1,Enter,External,28
0,0,13
1,2,Enter,External,57
0,0,2690
1,1,Exit,External,57
0,0,960
1,1,Resume,External,28
0,0,7
1,2,Enter,External,57
0,0,4409
1,1,Exit,External,57
0,0,961
1,2,Resume,External,28
0,0,7
1,1,Enter,External,57
0,0,4401
1,3,Exit,External,57
0,0,965
1,2,Resume,External,28
0,0,7
1,2,Enter,External,54
0,0,3950
1,2,Exit,External,54
0,0,361
1,6,Resume,External,28
0,0,7
1,2,Enter,External,57
0,0,80
1,2,Exit,External,57
0,0,965
1,1,Resume,External,28
0,0,7
1,2,Exit,External,28
0,0,412
```
In the above example, 28 is the interrupt I'm trying to measure, and 57 occurs a few times during it as a higher priority.  orbtop maxTicks appears to be only giving me the max single instance of 28 between the 57s, but really the exception is underway for the entire above trace.

Modifying orbtop like:
```
@@ -302,12 +304,12 @@ void _handleException( struct excMsg *m, struct ITMDecoder *i )
             break;
 
         case EXEVENT_RESUME: /* Unwind all levels of exception (deals with tail chaining) */
-            while ( ( _r.currentException != NO_EXCEPTION ) && ( _r.erDepth ) )
+            while ( ( _r.currentException != m->exceptionNumber ) && ( _r.erDepth ) )
             {
                 _exitEx( _r.timeStamp );
             }
 
-            _r.currentException = NO_EXCEPTION;
+//            _r.currentException = NO_EXCEPTION;
             break;

``` 
produces numbers far more aligned with my own measurements.  Am I misunderstanding something about the meaning of the trace messages, or is this the correct way to handle these events?

**Comment by mubes** [comment]
Addressed by #bdc3052  Thanks!!!
