### ISSUE TITLE
Weird help message for the orbtrace -T option

### ISSUE THREAD

**Issue by PetteriAimonen** [orbcode/orbuculum#92]
In version 5c711f40e from Devel branch, I get the following with `orbtrace --help`:

       -T, --trace-format:  <x> Trace format; 1,2 or 4 bit parallel, m for Manchester SWO, u=UART SWO
       -                         For UART, follow with speed, e.g. -Tu for Manchester SWO, u=UART SWO

with the message coming from here: https://github.com/orbcode/orbuculum/blob/Devel/Src/orbtrace.c#L144-L145

I don't understand what the second line means, looks like copy paste mistake to me.

**Comment by mubes** [comment]
Sorry for the delay, I missed this!  Thanks for the report. Now fixed via ce5e47a.
